[tool.commitizen]
name = "cz_conventional_commits"
version = "0.13.0"
tag_format = "v$version"
version_files = [
  "./brrrr/Cargo.toml",
  "./brrrr/src/main.rs",
  "./brrrr-lib/Cargo.toml",
  "./README.md",
]
