[tool.commitizen]
name = "cz_conventional_commits"
version = "0.8.2"
tag_format = "v$version"
version_files = [
  "./brrrr/Cargo.toml:version",
  "./brrrr/src/main.rs:version",
  "./brrrr-lib/Cargo.toml:version",
]
