[package]
authors = ["Trent Hauck <trent@trenthauck.com>"]
edition = "2021"
name = "brrrr"
version = "0.11.1"

[[bin]]
name = "brrrr"
path = "src/main.rs"

[dependencies]
brrrr-lib = {path = "../brrrr-lib"}
bio = "0.41"
argh = "0.1.6"

[dev-dependencies]
assert_cmd = "1.0.1"
