[package]
authors = ["Trent Hauck <trent@trenthauck.com>"]
edition = "2018"
name = "brrrr-lib"
version = "0.9.1"

[dependencies]
bio = {git = "https://github.com/rust-bio/rust-bio"}
itertools = "0.9.0"
parquet = "5.2.0"
arrow = "5.2.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
harness = false
name = "read_fasta"

[[example]]
name = "hello_world_parquet"
path = "examples/fa2jsonl.rs"
